# Generated by Django 6.0.2 on 2026-04-24 12:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(max_length=255, unique=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('type', models.CharField(default='GPS', max_length=100)),
                ('rear_camera_url', models.URLField(blank=True, max_length=500, null=True)),
                ('front_camera_url', models.URLField(blank=True, max_length=500, null=True)),
                ('features', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('accuracy', models.FloatField(blank=True, null=True)),
                ('speed', models.FloatField(blank=True, null=True)),
                ('altitude', models.FloatField(blank=True, null=True)),
                ('logged_at', models.DateTimeField(help_text='Event time from device (original source)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('type', models.CharField(default='', max_length=100)),
                ('value', models.CharField(blank=True, max_length=255, null=True)),
                ('device', models.ForeignKey(db_column='device_id', on_delete=django.db.models.deletion.CASCADE, related_name='events', to='devices.device', to_field='uuid')),
            ],
            options={
                'db_table': 'device_events',
                'indexes': [models.Index(fields=['device', 'logged_at'], name='device_even_device__9ceb15_idx'), models.Index(fields=['type'], name='device_even_type_de9e47_idx')],
            },
        ),
        migrations.CreateModel(
            name='Heartbeat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('speed', models.FloatField(blank=True, null=True)),
                ('altitude', models.FloatField(blank=True, null=True)),
                ('bearing', models.FloatField(blank=True, null=True)),
                ('logged_at', models.DateTimeField(help_text='Event time from device (original source)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(db_column='device_id', on_delete=django.db.models.deletion.CASCADE, related_name='heartbeats', to='devices.device', to_field='uuid')),
            ],
            options={
                'db_table': 'device_heartbeats',
                'indexes': [models.Index(fields=['device', 'logged_at'], name='device_hear_device__60fb92_idx')],
            },
        ),
    ]
