# Generated by Django 6.0.2 on 2026-04-24 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FleetKPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('total_vehicles', models.IntegerField(default=0)),
                ('available', models.IntegerField(default=0)),
                ('assigned', models.IntegerField(default=0)),
                ('maintenance', models.IntegerField(default=0)),
                ('offroad', models.IntegerField(default=0)),
                ('utilization', models.FloatField(default=0.0)),
                ('fuel_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('maintenance_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
            ],
        ),
    ]
