# Generated by Django 6.0.2 on 2026-04-24 12:34

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.CharField(max_length=100, unique=True)),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('cnic_number', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('rfid_tag', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('dob', models.DateField(blank=True, null=True)),
                ('license_number', models.CharField(blank=True, max_length=50, null=True)),
                ('license_type', models.CharField(blank=True, max_length=20, null=True)),
                ('license_expiry', models.DateField(blank=True, null=True)),
                ('is_available', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('off-duty', 'Off Duty'), ('on-break', 'On Break'), ('unavailable', 'Unavailable'), ('on-journey', 'On Journey')], default='active', help_text='Current driver status', max_length=20)),
                ('performance_score', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('medical_record', models.FileField(blank=True, null=True, upload_to='driver_medical/')),
                ('training_certificate', models.FileField(blank=True, null=True, upload_to='driver_training/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='drivers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DriverViolation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('violation_type', models.CharField(max_length=100)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('penalty_points', models.IntegerField(default=0)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='violations', to='drivers.driver')),
            ],
        ),
    ]
