# Generated by Django 6.0.2 on 2026-04-24 12:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('drivers', '0001_initial'),
        ('journeys', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverviolation',
            name='incident',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='driver_violations', to='journeys.incident'),
        ),
    ]
