# Generated by Django 5.2.4 on 2026-05-07 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('manager', 'Manager'), ('contractor', 'Contractor'), ('annotator', 'Annotator')], default='contractor', max_length=20),
        ),
    ]
