# Generated by Django 6.0.2 on 2026-04-24 12:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('drivers', '0001_initial'),
        ('fleet', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incident_type', models.CharField(choices=[('ACCIDENT', 'Accident'), ('SPEED_VIOLATION', 'Speed Violation'), ('VIOLATION', 'Driver Violation'), ('OTHER', 'Other')], default='OTHER', max_length=20)),
                ('description', models.TextField(default='')),
                ('date_occurred', models.DateTimeField()),
                ('repair_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('root_cause', models.TextField(blank=True, null=True)),
                ('gps_speed', models.FloatField(blank=True, null=True)),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='drivers.driver')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fleet.vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='Journey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('In Progress', 'In Progress'), ('Completed', 'Completed')], default='Pending', max_length=20)),
                ('lat', models.DecimalField(blank=True, decimal_places=6, default=0.0, max_digits=9, null=True)),
                ('lng', models.DecimalField(blank=True, decimal_places=6, default=0.0, max_digits=9, null=True)),
                ('suggested_route', models.TextField(blank=True, null=True)),
                ('actual_route', models.TextField(blank=True, null=True)),
                ('estimated_time', models.DurationField(blank=True, null=True)),
                ('actual_time', models.DurationField(blank=True, null=True)),
                ('estimated_fuel', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('actual_fuel', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('start_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='journeys', to='drivers.driver')),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fleet.vehicle')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PrimaryExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('type', models.CharField(choices=[('insurance', 'Insurance'), ('fuel', 'Fuel'), ('maintenance', 'Maintenance'), ('other', 'Other')], default='other', max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='fleet.vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='SecondaryExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('type', models.CharField(choices=[('toll', 'Toll'), ('operational', 'Operational'), ('challan', 'Challan'), ('other', 'Other')], default='other', max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('journey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='journeys.journey')),
            ],
        ),
    ]
