# Generated by Django 6.0.2 on 2026-04-24 12:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fleet', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tyre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(max_length=50, unique=True)),
                ('brand', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=50)),
                ('purchased_date', models.DateField()),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('current_position', models.CharField(choices=[('FL', 'Front Left'), ('FR', 'Front Right'), ('RL', 'Rear Left'), ('RR', 'Rear Right'), ('SPARE', 'Spare'), ('STORE', 'In Store')], default='STORE', max_length=10)),
                ('status', models.CharField(choices=[('MOUNTED', 'Mounted'), ('STOCK', 'In Stock'), ('SCRAPPED', 'Scrapped')], default='STOCK', max_length=20)),
                ('total_km_run', models.IntegerField(default=0, help_text='Aggregated from history')),
                ('current_vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tyres', to='fleet.vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='TyreHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(choices=[('FL', 'Front Left'), ('FR', 'Front Right'), ('RL', 'Rear Left'), ('RR', 'Rear Right'), ('SPARE', 'Spare'), ('STORE', 'In Store')], max_length=10)),
                ('install_date', models.DateField()),
                ('install_odometer', models.IntegerField()),
                ('remove_date', models.DateField(blank=True, null=True)),
                ('remove_odometer', models.IntegerField(blank=True, null=True)),
                ('tyre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='tyres.tyre')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fleet.vehicle')),
            ],
        ),
    ]
