# Generated by Django 6.0.2 on 2026-04-24 12:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('devices', '0001_initial'),
        ('fleet', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ViolationCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('violation_category_name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ViolationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_annotatable', models.BooleanField(default=False)),
                ('severity', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='violations', to='violations.violationcategory')),
            ],
        ),
        migrations.CreateModel(
            name='Violation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('speed', models.FloatField(blank=True, null=True)),
                ('accuracy', models.FloatField(blank=True, null=True)),
                ('altitude', models.FloatField(blank=True, null=True)),
                ('logged_at', models.DateTimeField(help_text='Event time from device (original source)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('front_camera_video_file_name', models.CharField(blank=True, max_length=255, null=True)),
                ('rear_camera_video_file_name', models.CharField(blank=True, max_length=255, null=True)),
                ('left_camera_video_file_name', models.CharField(blank=True, max_length=255, null=True)),
                ('right_camera_video_file_name', models.CharField(blank=True, max_length=255, null=True)),
                ('cabin_camera_video_file_name', models.CharField(blank=True, max_length=255, null=True)),
                ('driver_id', models.CharField(blank=True, max_length=100, null=True)),
                ('meta', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(default='unevaluated', max_length=100)),
                ('device', models.ForeignKey(db_column='device_id', on_delete=django.db.models.deletion.CASCADE, related_name='violations', to='devices.device', to_field='uuid')),
                ('user', models.ForeignKey(blank=True, db_column='user_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='violations', to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(blank=True, db_column='vehicle_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='violations', to='fleet.vehicle')),
                ('violation_type_id', models.ForeignKey(db_column='violation_id', on_delete=django.db.models.deletion.CASCADE, related_name='violations', to='violations.violationtype')),
            ],
            options={
                'db_table': 'device_violations',
            },
        ),
        migrations.CreateModel(
            name='ViolationAnnotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=100)),
                ('comment', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('annotated_by', models.ForeignKey(db_column='annotated_by', on_delete=django.db.models.deletion.CASCADE, related_name='violation_annotations', to=settings.AUTH_USER_MODEL)),
                ('violation', models.ForeignKey(db_column='violation_id', on_delete=django.db.models.deletion.CASCADE, related_name='annotations', to='violations.violation')),
            ],
            options={
                'db_table': 'violation_annotations',
                'indexes': [models.Index(fields=['violation', 'annotated_by', 'status', 'created_at'], name='violation_a_violati_5716d0_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='violation',
            index=models.Index(fields=['logged_at'], name='device_viol_logged__4123bc_idx'),
        ),
        migrations.AddIndex(
            model_name='violation',
            index=models.Index(fields=['status'], name='device_viol_status_69ce1b_idx'),
        ),
        migrations.AddIndex(
            model_name='violation',
            index=models.Index(fields=['user'], name='device_viol_user_id_2e9d63_idx'),
        ),
        migrations.AddIndex(
            model_name='violation',
            index=models.Index(fields=['vehicle'], name='device_viol_vehicle_b28c9c_idx'),
        ),
        migrations.AddIndex(
            model_name='violation',
            index=models.Index(fields=['violation_type_id'], name='device_viol_violati_217b18_idx'),
        ),
        migrations.AddIndex(
            model_name='violation',
            index=models.Index(fields=['device', 'logged_at', 'violation_type_id'], name='device_viol_device__e911b2_idx'),
        ),
    ]
